name: Lint Compiled Code

on: [push]

jobs:
  run-linters:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0
      
      - name: Install dependencies
        run: npm install

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          eslint_extensions: ts